# Generated by Django 2.1.3 on 2018-11-30 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_reduction', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField()),
                ('health', models.IntegerField()),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Enemy_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_class', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Enemy')),
            ],
        ),
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('rarity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8)])),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mineral_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_class', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Paired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Armor')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('health', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField()),
                ('durability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Person')),
            ],
        ),
        migrations.AddField(
            model_name='paired',
            name='weapon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Weapon'),
        ),
        migrations.AddField(
            model_name='mineral',
            name='mineral_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Mineral_type'),
        ),
        migrations.AddField(
            model_name='mineral',
            name='person_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='game.Person'),
        ),
        migrations.AddField(
            model_name='mineral',
            name='world_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existence', to='game.Person'),
        ),
        migrations.AddField(
            model_name='fight',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Person'),
        ),
        migrations.AddField(
            model_name='equip',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Paired'),
        ),
        migrations.AddField(
            model_name='equip',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Person'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='enemy_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Enemy_type'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='world_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Person'),
        ),
        migrations.AddField(
            model_name='armor',
            name='amount_modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Mineral_type'),
        ),
        migrations.AddField(
            model_name='armor',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Person'),
        ),
    ]
