# Generated by Django 2.1.3 on 2018-12-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='mineral_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Mineral_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armor',
            name='amount_modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Mineral_type'),
            preserve_default=False,
        ),
    ]
